name = "fantasy-story-generator"
main = "worker/index.ts"
compatibility_date = "2024-10-01"

# Uncomment and set a custom route if you have a domain
# routes = [
#   { pattern = "api.yourdomain.com/api/*", zone_name = "yourdomain.com" }
# ]